"""Build a PDF report with exhibit appendix pages.

Opens the existing report PDF (generated by md2pdf) and appends exhibit
pages showing highlighted source documents for each citation.
"""
from pathlib import Path

import fitz  # PyMuPDF

from app.config import REPORTS_DIR


def build_exhibit_report(report_path: Path, exhibits: list[dict]) -> Path | None:
    """Build a PDF with the report followed by exhibit appendix pages.

    Args:
        report_path: Path to the markdown landscape report.
        exhibits: List of exhibit dicts from generate_all_exhibits(),
                  each with keys: exhibit_number, board_code, meeting_date,
                  claim_text, exhibit_path.

    Returns:
        Path to the output PDF.
    """
    # Open the existing report PDF (generated by md2pdf)
    base_pdf = report_path.with_suffix(".pdf")
    if not base_pdf.exists():
        print(f"Base report PDF not found at {base_pdf}. Run md2pdf first.")
        return None

    report_doc = fitz.open(str(base_pdf))

    # Add exhibit separator page
    sep_page = report_doc.new_page(width=612, height=792)
    sep_page.insert_text(
        fitz.Point(200, 350),
        "EXHIBITS",
        fontsize=36,
        fontname="Helvetica-Bold",
        color=fitz.utils.getColor("navy"),
    )
    sep_page.insert_text(
        fitz.Point(140, 400),
        "Source Documents with Highlighted Evidence",
        fontsize=14,
        fontname="Helvetica",
        color=fitz.utils.getColor("gray50"),
    )

    # Add each exhibit as an appendix page
    added = 0
    for exhibit in exhibits:
        if not exhibit.get("exhibit_path"):
            continue

        exhibit_path = Path(exhibit["exhibit_path"])
        if not exhibit_path.exists():
            continue

        # Create a new page with header + exhibit image
        page = report_doc.new_page(width=612, height=792)

        # Header bar
        header_rect = fitz.Rect(0, 0, 612, 50)
        page.draw_rect(header_rect, color=None, fill=fitz.utils.getColor("navy"))
        page.insert_text(
            fitz.Point(20, 32),
            f"Exhibit {exhibit['exhibit_number']}",
            fontsize=16,
            fontname="Helvetica-Bold",
            color=fitz.utils.getColor("white"),
        )
        page.insert_text(
            fitz.Point(150, 32),
            f"{exhibit['board_code']}  |  {exhibit['meeting_date']}",
            fontsize=12,
            fontname="Helvetica",
            color=fitz.utils.getColor("lightskyblue"),
        )

        # Claim text (what the report says)
        claim = exhibit.get("claim_text", "")[:200]
        if claim:
            page.insert_textbox(
                fitz.Rect(20, 58, 592, 85),
                f'"{claim}..."',
                fontsize=8,
                fontname="Helvetica-Oblique",
                color=fitz.utils.getColor("gray40"),
            )

        # Insert the exhibit image (the highlighted PDF page)
        img_rect = fitz.Rect(20, 90, 592, 772)
        page.insert_image(img_rect, filename=str(exhibit_path))

        added += 1

    # Save
    output_name = report_path.stem + "-with-exhibits.pdf"
    output_path = REPORTS_DIR / output_name
    total_pages = len(report_doc)
    report_doc.ez_save(str(output_path))

    print(f"Built exhibit report: {output_path.name} ({added} exhibits, {total_pages} pages)")
    return output_path
